const mongoose = require('mongoose');
const dotenv = require('dotenv');
const path = require('path');

dotenv.config({ path: path.join(__dirname, '../.env') });

const User = require('../models/User');
const LevelIncome = require('../models/LevelIncome');
const { isUserEligible } = require('../utils/levelIncome25');

async function run() {
    try {
        const uri = process.env.MONGO_URI;
        if (!uri) throw new Error('MONGO_URI is missing');

        console.log('Connecting to database...');
        await mongoose.connect(uri);
        console.log('Connected.');

        // Find users
        const buyer = await User.findOne({ referral_id: { $regex: /^SGN9747$/i } });
        const sponsor1 = await User.findOne({ referral_id: { $regex: /^SGN9734$/i } });
        const sponsor2 = await User.findOne({ referral_id: { $regex: /^SGN9685$/i } });

        console.log('\n=== USER DETAILS ===');
        if (buyer) {
            console.log(`Buyer (SGN9747): _id=${buyer._id}, email=${buyer.email}, sponsor_id=${buyer.sponsor_id}, id=${buyer.id}, user_id=${buyer.user_id}`);
        } else {
            console.log('Buyer SGN9747 not found!');
        }

        if (sponsor1) {
            console.log(`Sponsor Level 1 (SGN9734): _id=${sponsor1._id}, email=${sponsor1.email}, sponsor_id=${sponsor1.sponsor_id}, is_deleted=${sponsor1.is_deleted}, id=${sponsor1.id}, user_id=${sponsor1.user_id}`);
            const isElig = await isUserEligible(sponsor1._id);
            console.log(`  --> isUserEligible: ${isElig}`);
        } else {
            console.log('Sponsor SGN9734 not found!');
        }

        if (sponsor2) {
            console.log(`Sponsor Level 2 (SGN9685): _id=${sponsor2._id}, email=${sponsor2.email}, sponsor_id=${sponsor2.sponsor_id}, is_deleted=${sponsor2.is_deleted}, id=${sponsor2.id}, user_id=${sponsor2.user_id}`);
            const isElig = await isUserEligible(sponsor2._id);
            console.log(`  --> isUserEligible: ${isElig}`);
        } else {
            console.log('Sponsor SGN9685 not found!');
        }

        // Fetch products for SGN9747
        if (buyer) {
            const buyerQueryIds = [buyer.id, buyer.user_id, buyer._id.toString(), 'SGN9747'].filter(Boolean);
            const products = await mongoose.connection.db.collection('products').find({
                user_id: { $in: buyerQueryIds },
                $or: [{ approve: 1 }, { approve: '1' }]
            }).toArray();

            console.log(`\n=== APPROVED PRODUCTS FOR SGN9747 ===`);
            console.log(`Found ${products.length} approved products:`);
            products.forEach((p, idx) => {
                console.log(`  [${idx+1}] Product: _id=${p._id}, type=${p.packag_type}, qty=${p.quantity}, amount=${p.amount}, date=${p.cereate_at || p.create_at}`);
            });

            // Fetch LevelIncomes from SGN9747
            const incomes = await LevelIncome.find({ from_user_id: { $in: buyerQueryIds } }).lean();
            console.log(`\n=== LEVEL INCOME ENTRIES GENERATED BY SGN9747 ===`);
            console.log(`Found ${incomes.length} level income entries:`);
            for (const inc of incomes) {
                const recipient = await User.findOne({
                    $or: [
                        { id: inc.user_id },
                        { user_id: inc.user_id },
                        { _id: mongoose.Types.ObjectId.isValid(inc.user_id) ? new mongoose.Types.ObjectId(inc.user_id) : null }
                    ].filter(q => q._id !== null || q.id || q.user_id)
                });
                console.log(`  Level ${inc.level}: to recipient email=${recipient?.email} (id=${recipient?.referral_id}), amount=${inc.amount}, date=${inc.create_at || inc.created_at}`);
            }
        }

        process.exit(0);
    } catch (err) {
        console.error('DIAGNOSTIC FAILED:', err.stack);
        process.exit(1);
    }
}
run();
