const mongoose = require('mongoose');
require('dotenv').config();

async function checkPrayag() {
    try {
        await mongoose.connect(process.env.MONGODB_URL || process.env.MONGO_URI);
        const User = mongoose.model('User', new mongoose.Schema({}, { strict: false }));
        const Product = mongoose.model('Product', new mongoose.Schema({}, { strict: false }));
        const ReferralIncomes = mongoose.model('ReferralIncomes', new mongoose.Schema({}, { strict: false }));

        // 1. Find Prayag
        const prayag = await User.findOne({ referral_id: 'SGN9924' });
        if (!prayag) {
            console.log('User SGN9924 not found.');
            process.exit(0);
        }

        console.log(`User: ${prayag.full_name} (${prayag.referral_id})`);
        console.log(`Sponsor ID: ${prayag.sponsor_id}`);

        // 2. Find Sponsor Name
        const sponsor = await User.findOne({ 
            $or: [{ referral_id: prayag.sponsor_id }, { id: prayag.sponsor_id }, { user_id: prayag.sponsor_id }]
        });
        console.log(`Sponsor Name: ${sponsor ? sponsor.full_name : 'Unknown'} (${prayag.sponsor_id})`);

        // 3. Find Prayag's Products (All status)
        const prayagId = prayag.id || prayag.user_id || prayag._id.toString();
        const products = await Product.find({
            user_id: { $in: [prayagId, prayag._id.toString(), 'SGN9924'] }
        });

        console.log(`\nFound ${products.length} products (All Status) for Prayag:`);
        
        let totalSponsorIncomeExpected = 0;

        for (const p of products) {
            const amount = p.amount * (p.quantity || 1);
            const expected = amount * 0.08;
            totalSponsorIncomeExpected += expected;
            
            console.log(`- Product: ${p.packag_type} | Total Amount: ₹${amount} | Expected Sponsor Income (8%): ₹${expected}`);

            // Check actual records
            const records = await ReferralIncomes.find({
                $or: [
                    { product_id: p._id },
                    { product_transcation_id: p.transcation_id }
                ]
            });

            if (records.length > 0) {
                records.forEach(r => {
                    console.log(`  [RECORD] To: ${r.user_id} | Amount: ₹${r.referral_amount} | Date: ${r.create_at}`);
                });
            } else {
                console.log(`  [ALERT] No Referral Income record found for this product!`);
            }
        }

        console.log(`\nTotal Sponsor Income generated by Prayag: ₹${totalSponsorIncomeExpected}`);

        process.exit(0);
    } catch (err) {
        console.error(err);
        process.exit(1);
    }
}

checkPrayag();
